### ISSUE TITLE
Package maps not in GOROOT

### ISSUE THREAD

**Issue by jeremiah** [protobom/protobom#220]
Hello,

When running the code listed in the README, I get the following errors;
```
../../../go/pkg/mod/github.com/bom-squad/protobom@v0.3.0/pkg/sbom/externalreference.go:5:2: package maps is not in GOROOT (/usr/lib/go-1.19/src/maps)
../../../go/pkg/mod/github.com/bom-squad/protobom@v0.3.0/pkg/sbom/diff.go:4:2: package slices is not in GOROOT (/usr/lib/go-1.19/src/slices)
```
My version of go is `go1.19.8 linux/amd64` - do I need a newer go?

**Comment by jeremiah** [comment]
Upgraded to go1.22.3 and that solved the issue.

**Comment by puerco** [comment]
Correct! protobom needs go 1.22 (perhaps we should note that somewhere in the docs :) )
https://github.com/protobom/protobom/blob/8e47a21ca3e44629f5938219e0de5b72c342b9d3/go.mod#L1-L4
