### ISSUE TITLE
Support for CycloneDX 1.6

### ISSUE THREAD

**Issue by ursachec** [protobom/protobom#226]
Hello maintainers! First of all, thank you for this wonderful library.
Second, I have a question: do you plan on adding support for CycloneDX 1.6 in the near future?
Thank you and all best

**Comment by manifestori** [comment]
Hi @ursachec, thank you for reaching out :) 

our support for cdx1.6 is dependent on https://github.com/CycloneDX/cyclonedx-go/issues/140
as the underlying cdx library.

Once the support (experimental/stable) for cdx 1.6 is implemented, we will add a serializer/unserializer for it

**Comment by ursachec** [comment]
Got it. That you for the response @manifestori!

**Comment by VinodAnandan** [comment]
@manifestori The CycloneDX Go library version 0.9.0, released on June 4th ([CycloneDX/cyclonedx-go@v0.9.0](https://github.com/CycloneDX/cyclonedx-go/releases/tag/v0.9.0)), includes support for CycloneDX 1.6. Is the support for CycloneDX 1.6 still being considered, or are there other blockers?

Cc: @jhoward-lm, @idunbarh, @stevespringett, @nscuro
